[2025-06-29T04:54:48.665+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-28T18:47:00+00:00 [queued]>
[2025-06-29T04:54:48.685+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-28T18:47:00+00:00 [queued]>
[2025-06-29T04:54:48.686+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-29T04:54:48.789+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_etl_script> on 2025-06-28 18:47:00+00:00
[2025-06-29T04:54:48.796+0000] {standard_task_runner.py:60} INFO - Started process 4736 to run task
[2025-06-29T04:54:48.801+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'films_dag_orchestaror', 'run_etl_script', 'scheduled__2025-06-28T18:47:00+00:00', '--job-id', '1290', '--raw', '--subdir', 'DAGS_FOLDER/orchestrator.py', '--cfg-path', '/tmp/tmp3r7wde1w']
[2025-06-29T04:54:48.804+0000] {standard_task_runner.py:88} INFO - Job 1290: Subtask run_etl_script
[2025-06-29T04:54:48.916+0000] {task_command.py:423} INFO - Running <TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-28T18:47:00+00:00 [running]> on host 1b1e07855000
[2025-06-29T04:54:49.055+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='films_dag_orchestaror' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T18:47:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-28T18:47:00+00:00'
[2025-06-29T04:54:49.210+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/orchestrator.py", line 18, in run_etl_script
    raise Exception(result.stderr)
Exception: pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.5 (Debian 17.5-1.pgdg120+1); pg_dump version: 16.2 (Debian 16.2-1.pgdg120+2)
Traceback (most recent call last):
  File "/opt/airflow/etl/etl.py", line 61, in <module>
    subprocess.run(dump_comand,env=subprocess_env,check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pg_dump', '-h', 'source_postgres', '-U', 'postgres', '-d', 'source_db', '-f', 'data_dump.sql', '-w']' returned non-zero exit status 1.

[2025-06-29T04:54:49.225+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=films_dag_orchestaror, task_id=run_etl_script, execution_date=20250628T184700, start_date=20250629T045448, end_date=20250629T045449
[2025-06-29T04:54:49.237+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1290 for task run_etl_script (pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.5 (Debian 17.5-1.pgdg120+1); pg_dump version: 16.2 (Debian 16.2-1.pgdg120+2)
Traceback (most recent call last):
  File "/opt/airflow/etl/etl.py", line 61, in <module>
    subprocess.run(dump_comand,env=subprocess_env,check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pg_dump', '-h', 'source_postgres', '-U', 'postgres', '-d', 'source_db', '-f', 'data_dump.sql', '-w']' returned non-zero exit status 1.
; 4736)
[2025-06-29T04:54:49.270+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-29T04:54:49.292+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-29T05:37:36.986+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-28T18:47:00+00:00 [queued]>
[2025-06-29T05:37:37.008+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-28T18:47:00+00:00 [queued]>
[2025-06-29T05:37:37.009+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-29T05:37:37.056+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_etl_script> on 2025-06-28 18:47:00+00:00
[2025-06-29T05:37:37.064+0000] {standard_task_runner.py:60} INFO - Started process 7010 to run task
[2025-06-29T05:37:37.070+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'films_dag_orchestaror', 'run_etl_script', 'scheduled__2025-06-28T18:47:00+00:00', '--job-id', '1131', '--raw', '--subdir', 'DAGS_FOLDER/orchestrator.py', '--cfg-path', '/tmp/tmproxs16ga']
[2025-06-29T05:37:37.074+0000] {standard_task_runner.py:88} INFO - Job 1131: Subtask run_etl_script
[2025-06-29T05:37:37.186+0000] {task_command.py:423} INFO - Running <TaskInstance: films_dag_orchestaror.run_etl_script scheduled__2025-06-28T18:47:00+00:00 [running]> on host b83c7b21874f
[2025-06-29T05:37:37.315+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='films_dag_orchestaror' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T18:47:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-28T18:47:00+00:00'
[2025-06-29T05:37:37.582+0000] {logging_mixin.py:188} INFO - --
-- PostgreSQL database dump
--
-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)
SET statement_timeout = 0;
SET
SET lock_timeout = 0;
SET
SET idle_in_transaction_session_timeout = 0;
SET
SET transaction_timeout = 0;
SET
SET client_encoding = 'UTF8';
SET
SET standard_conforming_strings = on;
SET
SELECT pg_catalog.set_config('search_path', '', false);
 set_config 
------------
 
(1 row)

SET check_function_bodies = false;
SET
SET xmloption = content;
SET
SET client_min_messages = warning;
SET
SET row_security = off;
SET
SET default_tablespace = '';
SET
SET default_table_access_method = heap;
SET
--
-- Name: actors; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.actors (
    actor_id integer NOT NULL,
    actor_name character varying(255) NOT NULL
);
ALTER TABLE public.actors OWNER TO postgres;
ALTER TABLE
--
-- Name: actors_actor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
CREATE SEQUENCE public.actors_actor_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.actors_actor_id_seq OWNER TO postgres;
ALTER SEQUENCE
--
-- Name: actors_actor_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--
ALTER SEQUENCE public.actors_actor_id_seq OWNED BY public.actors.actor_id;
ALTER SEQUENCE
--
-- Name: film_actors; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.film_actors (
    film_id integer NOT NULL,
    actor_id integer NOT NULL
);
ALTER TABLE public.film_actors OWNER TO postgres;
ALTER TABLE
--
-- Name: film_category; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.film_category (
    category_id integer NOT NULL,
    film_id integer,
    category_name character varying(50) NOT NULL
);
ALTER TABLE public.film_category OWNER TO postgres;
ALTER TABLE
--
-- Name: film_category_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
CREATE SEQUENCE public.film_category_category_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.film_category_category_id_seq OWNER TO postgres;
ALTER SEQUENCE
--
-- Name: film_category_category_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--
ALTER SEQUENCE public.film_category_category_id_seq OWNED BY public.film_category.category_id;
ALTER SEQUENCE
--
-- Name: films; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.films (
    film_id integer NOT NULL,
    title character varying(255) NOT NULL,
    release_date date,
    price numeric(5,2),
    rating character varying(10),
    user_rating numeric(2,1),
    CONSTRAINT films_user_rating_check CHECK (((user_rating >= (1)::numeric) AND (user_rating <= (5)::numeric)))
);
ALTER TABLE public.films OWNER TO postgres;
ALTER TABLE
--
-- Name: films_film_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
CREATE SEQUENCE public.films_film_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.films_film_id_seq OWNER TO postgres;
ALTER SEQUENCE
--
-- Name: films_film_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--
ALTER SEQUENCE public.films_film_id_seq OWNED BY public.films.film_id;
ALTER SEQUENCE
--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.users (
    id integer NOT NULL,
    first_name character varying(50),
    last_name character varying(50),
    email character varying(100),
    date_of_birth date
);
ALTER TABLE public.users OWNER TO postgres;
ALTER TABLE
--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.users_id_seq OWNER TO postgres;
ALTER SEQUENCE
--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--
ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;
ALTER SEQUENCE
--
-- Name: actors actor_id; Type: DEFAULT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.actors ALTER COLUMN actor_id SET DEFAULT nextval('public.actors_actor_id_seq'::reg
Succesfully connection with postgres..
Starting ETL script...
Ending ETL script..
[2025-06-29T05:37:37.582+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-29T05:37:37.596+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=films_dag_orchestaror, task_id=run_etl_script, execution_date=20250628T184700, start_date=20250629T053736, end_date=20250629T053737
[2025-06-29T05:37:37.629+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-29T05:37:37.649+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
